[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[window]
opacity=0.85

[terminal]

[terminal.shell]
program = "/run/current-system/sw/bin/bash"
args = ["-c", "neofetch; exec bash"]
